- name: Setup nginx server on my-server list(host group)
  hosts: my-servers
  become: True
  tasks:
    - name: Install the latest version of nginx
      command: amazon-linux-extras install nginx1.12=latest -y
      args:
        creates: /sibn/nginx

    - name: Start nginx service
      service:
        name: nginx
        state: started

    - name: Enable nginx service
      service:
        name: nginx
        enabled: yes
    
    - name: Get nginx installed version
      command: nginx -v

    - name: Get status of nginx service
      command: systemctl status nginx
    
    - name: Ansible copy file to remote server
      copy:
        src: /home/ec2-user/sample.txt
        dest: /home/ec2-user